# Tratamento de Dados

In [1]:
import pandas as pd

In [13]:
insurance = pd.read_csv('../arquivos/insurance.csv')
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

Inserindo itens na coluna

In [15]:
insurance['ano'] = 2025

In [16]:
insurance.head()

   age     sex     bmi  children smoker     region      charges   ano
0   19  female  27.900         0    yes  southwest  16884.92400  2025
1   18    male  33.770         1     no  southeast   1725.55230  2025
2   28    male  33.000         3     no  southeast   4449.46200  2025
3   33    male  22.705         0     no  northwest  21984.47061  2025
4   32    male  28.880         0     no  northwest   3866.85520  2025

In [17]:
insurance['coluna_nova'] = insurance['children']*2
insurance.head()

,age,sex,bmi,children,smoker,region,charges,ano,coluna_nova
0,19,female,27.900,0,yes,southwest,16884.92400,2025,0
1,18,male,33.770,1,no,southeast,1725.55230,2025,2
2,28,male,33.000,3,no,southeast,4449.46200,2025,6
3,33,male,22.705,0,no,northwest,21984.47061,2025,0
4,32,male,28.880,0,no,northwest,3866.85520,2025,0

In [ ]:
# removendo coluna
# O inplace serve para substituir no dataset as alterações feitas 
insurance.drop(columns=['ano', 'coluna_nova'], inplace=True)

In [21]:
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
# modificando valores de uma coluna
insurance.loc[0:3, 'sex'] = "male"

# para modificar vários valores, passe uma lista de valores
# insurance.loc[0:3, 'sex'] = ["male", "female", "female"]

In [24]:
insurance.head()

   age   sex     bmi  children smoker     region      charges
0   19  male  27.900         0    yes  southwest  16884.92400
1   18  male  33.770         1     no  southeast   1725.55230
2   28  male  33.000         3     no  southeast   4449.46200
3   33  male  22.705         0     no  northwest  21984.47061
4   32  male  28.880         0     no  northwest   3866.85520

## Tratamento com condicionais