# Exercício de Filtros

In [2]:
import pandas as pd

df = pd.read_csv('./arquivos/insurance.csv')

1. Quantas pessoas possuem filhos?

In [32]:
df.loc[df['children'] > 0].shape[0]

764

2. Selecione as linhas da posição 100 até a 120, mantendo apenas as colunas `age`, `bmi` e `charges`.

In [34]:
df.loc[100:120, ['age', 'bmi', 'charges']]

     age     bmi      charges
100   41  31.600   6186.12700
101   30  25.460   3645.08940
102   18  30.115  21344.84670
103   61  29.920  30942.19180
104   34  27.500   5003.85300
105   20  28.025  17560.37975
106   19  28.400   2331.51900
107   26  30.875   3877.30425
108   29  27.940   2867.11960
109   63  35.090  47055.53210
110   54  33.630  10825.25370
111   55  29.700  11881.35800
112   37  30.800   4646.75900
113   21  35.720   2404.73380
114   52  32.205  11488.31695
115   60  28.595  30259.99556
116   58  49.060  11381.32540
117   29  27.940  19107.77960
118   49  27.170   8601.32930
119   37  23.370   6686.43130
120   44  37.100   7740.33700

3. Quantas mulheres estão na região `southeast`?

In [12]:
df.loc[(df['sex'] == 'female') & (df['region'] == 'southeast')].shape[0]

175

4. Selecione apenas os homens com IMC (`bmi`) acima de 30.

In [14]:
df.loc[
    (df['sex'] == 'male')
    &
    (df['bmi'] > 30)
]

      age   sex     bmi  children smoker     region      charges
1      18  male  33.770         1     no  southeast   1725.55230
2      28  male  33.000         3     no  southeast   4449.46200
12     23  male  34.400         0     no  southwest   1826.84300
14     27  male  42.130         0    yes  southeast  39611.75770
18     56  male  40.300         0     no  southwest  10602.38500
...   ...   ...     ...       ...    ...        ...          ...
1322   62  male  38.830         0     no  southeast  12981.34570
1325   61  male  33.535         0     no  northeast  13143.33665
1327   51  male  30.030         1     no  southeast   9377.90470
1329   52  male  38.600         2     no  southwest  10325.20600
1333   50  male  30.970         3     no  northwest  10600.54830

[371 rows x 7 columns]

5. Use `query` para filtrar pessoas com `age > 40` e `charges > 20000`.

In [15]:
df.query("age > 40 and charges > 20000")

      age     sex     bmi  children smoker     region      charges
9      60  female  25.840         0     no  northwest  28923.13692
11     62  female  26.290         0    yes  southeast  27808.72510
39     60    male  39.900         0    yes  southwest  48173.36100
45     55    male  37.300         0     no  southwest  20630.28351
52     48    male  28.000         1    yes  southwest  23568.27200
...   ...     ...     ...       ...    ...        ...          ...
1303   43    male  27.800         0    yes  southwest  37829.72420
1304   42    male  24.605         2    yes  northeast  21259.37795
1321   62    male  26.695         0    yes  northeast  28101.33305
1323   42  female  40.370         2    yes  southeast  43896.37630
1337   61  female  29.070         0    yes  northwest  29141.36030

[161 rows x 7 columns]

6. Filtre com `loc` todas as pessoas fumantes com mais de 30 anos e que têm pelo menos 1 filho.

In [35]:
df.loc[
    (df['smoker'] == 'yes')
    &
    (df['age'] > 30)
    &
    (df['children'] > 0)
]

      age     sex     bmi  children smoker     region      charges
23     34  female  31.920         1    yes  northeast  37701.87680
29     31    male  36.300         2    yes  southwest  38711.00000
38     35    male  36.670         1    yes  northeast  39774.27630
49     36    male  35.200         1    yes  southeast  38709.17600
52     48    male  28.000         1    yes  southwest  23568.27200
...   ...     ...     ...       ...    ...        ...          ...
1284   61    male  36.300         1    yes  southwest  47403.88000
1301   62    male  30.875         3    yes  northwest  46718.16325
1304   42    male  24.605         2    yes  northeast  21259.37795
1307   32    male  28.120         4    yes  northwest  21472.47880
1323   42  female  40.370         2    yes  southeast  43896.37630

[118 rows x 7 columns]

7. Usando `query`, selecione pessoas da região `southwest` que não são fumantes e têm IMC entre 25 e 35.

In [20]:
df.query("region == 'southwest' and smoker == 'no' and 25 <= bmi <= 35")

      age     sex   bmi  children smoker     region      charges
12     23    male  34.4         0     no  southwest   1826.84300
21     30  female  32.4         1     no  southwest   4149.73600
32     19  female  28.6         5     no  southwest   4687.79700
65     19  female  28.9         0     no  southwest   1743.21400
72     53  female  28.1         3     no  southwest  11741.72600
...   ...     ...   ...       ...    ...        ...          ...
1269   45    male  27.5         3     no  southwest   8615.30000
1287   36  female  25.9         1     no  southwest   5472.44900
1309   41    male  32.2         2     no  southwest   6875.96100
1331   23  female  33.4         0     no  southwest  10795.93733
1336   21  female  25.8         0     no  southwest   2007.94500

[164 rows x 7 columns]

8. Filtre todos os registros onde o número de filhos é par e o valor de `charges` está entre 10.000 e 20.000.

In [ ]:
df.query("children % 2 == 0 and 10000 <= charges <= 20000")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
13     56  female  39.820         0     no  southeast  11090.71780
18     56    male  40.300         0     no  southwest  10602.38500
20     60  female  36.005         0     no  northeast  13228.84695
26     63  female  23.085         0     no  northeast  14451.83515
...   ...     ...     ...       ...    ...        ...          ...
1322   62    male  38.830         0     no  southeast  12981.34570
1325   61    male  33.535         0     no  northeast  13143.33665
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733

[240 rows x 7 columns]

In [37]:
df.loc[(df['children'] % 2 == 0)
       &
       (df['charges'].between(10000, 20000))
]

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
13     56  female  39.820         0     no  southeast  11090.71780
18     56    male  40.300         0     no  southwest  10602.38500
20     60  female  36.005         0     no  northeast  13228.84695
26     63  female  23.085         0     no  northeast  14451.83515
...   ...     ...     ...       ...    ...        ...          ...
1322   62    male  38.830         0     no  southeast  12981.34570
1325   61    male  33.535         0     no  northeast  13143.33665
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733

[240 rows x 7 columns]

9. Use `iloc` para obter as últimas 10 linhas e as 4 primeiras colunas.

In [38]:
df.iloc[-10:, :4]

      age     sex     bmi  children
1328   23  female  24.225         2
1329   52    male  38.600         2
1330   57  female  25.740         2
1331   23  female  33.400         0
1332   52  female  44.700         3
1333   50    male  30.970         3
1334   18  female  31.920         0
1335   18  female  36.850         0
1336   21  female  25.800         0
1337   61  female  29.070         0

10. Usando `query`, filtre pessoas com mais de 3 filhos, que sejam fumantes, e estejam na região `northeast` ou `northwest`.

In [31]:
df.query("children > 3 and smoker == 'yes' and (region == 'northeast' or  region == 'northwest')")

      age   sex    bmi  children smoker     region     charges
1307   32  male  28.12         4    yes  northwest  21472.4788